#SPDX-License-Identifier: MIT-0
---
# tasks file for front_php
- name: Executer la task si le hostname correspond
  ansible.builtin.include_tasks:
    file: install.yml
  when: "'web' in group_names"
