services:
  web1:
    image: ubuntu:24.04
    container_name: web1
    command: bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 && chmod 1777 /tmp && tail -f /dev/null"
    hostname: web1
    networks:
      - private-network

  web2:
    image: ubuntu:24.04
    container_name: web2
    command: bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 && chmod 1777 /tmp && tail -f /dev/null"
    hostname: web2
    networks:
      - private-network

  web3:
    image: ubuntu:24.04
    container_name: web3
    command: bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 && chmod 1777 /tmp && tail -f /dev/null"
    hostname: web3
    networks:
      - private-network

  db1:
    image: ubuntu:24.04
    container_name: db1
    command: bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 && chmod 1777 /tmp && tail -f /dev/null"
    hostname: db1
    networks:
      - private-network

  lb1:
    image: ubuntu:24.04
    container_name: lb1
    command: bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 && chmod 1777 /tmp && tail -f /dev/null"
    hostname: lb1
    networks:
      - private-network
    ports:
      - "8080:80"

networks:
  private-network:
    driver: bridge
