#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx
- name: Installer Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Démarrer Nginx si pas déjà lancé
  ansible.builtin.shell: pgrep -x nginx || nginx