#SPDX-License-Identifier: MIT-0
---
# tasks file for haproxy
- name: Executer la task si le hostname correspond
  ansible.builtin.include_tasks:
    file: setup.yml
  when: "'loadbalancer' in group_names"
